import 'package:flutter/material.dart';
import 'setting1.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Main(),
        ]),
      ),
    );
  }
}

class Main extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(
            image: DecorationImage(
              image: AssetImage("assets/Background/PinkBG.png"),
              fit: BoxFit.fill,
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 124,
                top: 142,
                child: Text(
                  'MINGLE',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 40,
                    fontFamily: 'assets/ONE Mobile POP OTF.otf',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Center(
                child: Container(
                  width: 338,
                  height: 336,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/BackGround/Circle.png"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 27,
                top: 238,
                child: Container(
                  width: 332,
                  height: 345,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 205,
                        top: 176,
                        child: Container(
                          width: 127,
                          height: 123,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image:
                                  AssetImage("assets/Character/pcharacter.png"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 95,
                          height: 93,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: AssetImage("assets/Character/bcharacter.png"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 53,
                top: 706,
                child: Container(
                  width: 287.01,
                  height: 101,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 117,
                        top: 49,
                        child: GestureDetector(
                          onTap: () {
                            Navigator.push(
                                context,
                                MaterialPageRoute(builder: (context) => Setting1())
                            );
                          },
                          child: Stack(
                            children: [
                              Center(
                                child: Container(
                                  width: 52,    // 로고의 너비
                                  height: 52,   // 로고의 높이
                                  decoration: BoxDecoration(
                                    shape: BoxShape.circle, // 원 모양
                                    color: Colors.white,     // 원의 색상
                                  ),
                                  child: Image.asset(
                                    'assets/Icon/google_logo.png',
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 198,
                        top: 12,
                        child: Container(
                          width: 89.01,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: Colors.white,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 12,
                        child: Container(
                          width: 89.01,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: Colors.white,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 88,
                        top: 0,
                        child: SizedBox(
                          width: 110,
                          child: Text(
                            'Login with',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 15,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 131,
                        top: 62,
                        child: Container(
                          width: 25,
                          height: 24.93,
                          child: Stack(children: [
                              ]),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}