import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Story1(),
        ]),
      ),
    );
  }
}

class Story1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(
            color: Colors.black.withOpacity(0.20000000298023224),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 32,
                top: 221.70,
                child: Container(
                  width: 328.78,
                  height: 487.30,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 170.26,
                        top: 0,
                        child: Container(
                          width: 158.52,
                          height: 231.91,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 1.57,
                                top: 207.13,
                                child: SizedBox(
                                  width: 156.20,
                                  height: 24.78,
                                  child: Text(
                                    '효녀 심청',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Color(0xFFEB93AA),
                                      fontSize: 17,
                                      fontFamily: 'ONE Mobile POP OTF',
                                      fontWeight: FontWeight.w400,
                                      height: 0.08,
                                      letterSpacing: 0.17,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 158.52,
                                  height: 200.60,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFD9D9D9),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(width: 4, color: Color(0xFFF9F9F9)),
                                      borderRadius: BorderRadius.circular(17),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 11.74,
                                top: 184.94,
                                child: Container(
                                  width: 133.08,
                                  height: 7.83,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFF9F9F9),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(54),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 170.26,
                        top: 254.41,
                        child: Container(
                          width: 158.52,
                          height: 231.91,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 1.57,
                                top: 207.13,
                                child: SizedBox(
                                  width: 156.20,
                                  height: 24.78,
                                  child: Text(
                                    '견우 직녀',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Color(0xFFEB93AA),
                                      fontSize: 17,
                                      fontFamily: 'ONE Mobile POP OTF',
                                      fontWeight: FontWeight.w400,
                                      height: 0.08,
                                      letterSpacing: 0.17,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 158.52,
                                  height: 200.60,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFD9D9D9),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(width: 4, color: Color(0xFFF9F9F9)),
                                      borderRadius: BorderRadius.circular(17),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 11.74,
                                top: 184.94,
                                child: Container(
                                  width: 133.08,
                                  height: 7.83,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFF9F9F9),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(54),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 255.39,
                        child: Container(
                          width: 158.52,
                          height: 231.91,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 1.57,
                                top: 207.13,
                                child: SizedBox(
                                  width: 156.20,
                                  height: 24.78,
                                  child: Text(
                                    '콩쥐 팥쥐',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Color(0xFFEB93AA),
                                      fontSize: 17,
                                      fontFamily: 'ONE Mobile POP OTF',
                                      fontWeight: FontWeight.w400,
                                      height: 0.08,
                                      letterSpacing: 0.17,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 158.52,
                                  height: 200.60,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFD9D9D9),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(width: 4, color: Color(0xFFF9F9F9)),
                                      borderRadius: BorderRadius.circular(17),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 11.74,
                                top: 184.94,
                                child: Container(
                                  width: 133.08,
                                  height: 7.83,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFF9F9F9),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(54),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 22,
                top: 208,
                child: Container(
                  width: 169.12,
                  height: 245.61,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 6.46,
                        top: 220.83,
                        child: SizedBox(
                          width: 156.20,
                          height: 24.78,
                          child: Text(
                            '선녀와 나무꾼',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFFEB93AA),
                              fontSize: 17,
                              fontFamily: 'ONE Mobile POP OTF',
                              fontWeight: FontWeight.w400,
                              height: 0.08,
                              letterSpacing: 0.17,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 169.12,
                          height: 213.29,
                          decoration: ShapeDecoration(
                            color: Color(0xFFD9D9D9),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(width: 4, color: Color(0xFFFEE7AD)),
                              borderRadius: BorderRadius.circular(17),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 13.70,
                        top: 196.68,
                        child: Container(
                          width: 140.91,
                          height: 8.81,
                          decoration: ShapeDecoration(
                            color: Color(0xFFF9F9F9),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(54),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 30,
                top: 133,
                child: Container(
                  width: 333,
                  height: 47,
                  decoration: ShapeDecoration(
                    color: Color(0xFFF9F9F9),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(34),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 347,
                top: 60,
                child: Container(
                  width: 22,
                  height: 22,
                  child: Stack(children: [
                      ,
                      ]),
                ),
              ),
              Positioned(
                left: 34,
                top: 57,
                child: Container(
                  width: 206,
                  height: 50,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 101,
                        top: 26,
                        child: Container(
                          width: 105,
                          height: 17,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              side: BorderSide(width: 2, color: Color(0xFFFEE7AD)),
                              borderRadius: BorderRadius.circular(54),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 105,
                        top: 30,
                        child: Container(
                          width: 94,
                          height: 9,
                          decoration: ShapeDecoration(
                            color: Color(0xFFEB93AA),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(54),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 50,
                          height: 50,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/50x50"),
                              fit: BoxFit.fill,
                            ),
                            shape: OvalBorder(
                              side: BorderSide(
                                width: 2,
                                strokeAlign: BorderSide.strokeAlignOutside,
                                color: Color(0xFFD4F6FF),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 63,
                        top: 5,
                        child: Text(
                          '밍글맘',
                          style: TextStyle(
                            color: Color(0xFFF9F9F9),
                            fontSize: 16,
                            fontFamily: 'ONE Mobile POP OTF',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 63,
                        top: 24,
                        child: Text(
                          'LV. 1',
                          style: TextStyle(
                            color: Color(0xFFFEE7AD),
                            fontSize: 14,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 0,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 233,
                top: 700,
                child: Container(
                  width: 151,
                  height: 151,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/151x151"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 795,
                child: SizedBox(
                  width: 116,
                  height: 12,
                  child: Text(
                    'Words',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF9D9D9D),
                      fontSize: 20,
                      fontFamily: 'ONE Mobile POP OTF',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 45.59,
                top: 748.95,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-0.13),
                  child: Container(
                    width: 57.67,
                    height: 43.28,
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0.04,
                          top: 0.16,
                          child: Transform(
                            transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-0.14),
                            child: Container(
                              width: 57.68,
                              height: 43.12,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 0.03,
                                    top: 0.17,
                                    child: Transform(
                                      transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-0.14),
                                      child: Container(
                                        width: 57.67,
                                        height: 42.95,
                                        decoration: BoxDecoration(
                                          image: DecorationImage(
                                            image: NetworkImage("https://via.placeholder.com/58x43"),
                                            fit: BoxFit.cover,
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0.03,
                                    top: 0.14,
                                    child: Transform(
                                      transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-0.14),
                                      child: Container(
                                        width: 57.66,
                                        height: 42.97,
                                        decoration: BoxDecoration(
                                          image: DecorationImage(
                                            image: NetworkImage("https://via.placeholder.com/58x43"),
                                            fit: BoxFit.cover,
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 256,
                top: 796,
                child: SizedBox(
                  width: 111,
                  height: 9,
                  child: Text(
                    'Story',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF5CA57B),
                      fontSize: 20,
                      fontFamily: 'ONE Mobile POP OTF',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 286,
                top: 741,
                child: Container(
                  width: 51.65,
                  height: 55.35,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: -5.52,
                        child: Container(
                          width: 51.65,
                          height: 55.35,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 51.65,
                                  height: 55.35,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/52x55"),
                                      fit: BoxFit.cover,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 51.65,
                                  height: 55.35,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/52x55"),
                                      fit: BoxFit.cover,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 156,
                top: 745,
                child: Container(
                  width: 81.38,
                  height: 75.71,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/81x76"),
                      fit: BoxFit.fill,
                    ),
                    boxShadow: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 215,
                top: 732,
                child: Container(
                  width: 20,
                  height: 20,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/20x20"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 84,
                top: 145,
                child: SizedBox(
                  width: 158.55,
                  child: Text(
                    '제목 검색...',
                    style: TextStyle(
                      color: Color(0xFF9D9D9D),
                      fontSize: 17,
                      fontFamily: 'Pretendard',
                      fontWeight: FontWeight.w500,
                      height: 0.08,
                      letterSpacing: 0.17,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 36,
                top: 138,
                child: Container(
                  width: 37,
                  height: 37,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 37,
                          height: 37,
                          decoration: ShapeDecoration(
                            color: Color(0xFFEB93AA),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(55),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 8.57,
                        top: 8.12,
                        child: Container(
                          width: 20.30,
                          height: 20.30,
                          padding: const EdgeInsets.symmetric(horizontal: 3.81),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Container(
                                width: 12.69,
                                height: 20.30,
                                child: Stack(children: [
                                    ,
                                    ]),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}